################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
ASM_SRCS += \
../src/BootLoader.asm \
../src/DSP2803x_CSMPasswords.asm \
../src/DSP2803x_CodeStartBranch.asm \
../src/DSP2803x_DBGIER.asm \
../src/DSP2803x_DisInt.asm \
../src/DSP2803x_usDelay.asm \
../src/boot_start.asm \
../src/dv64_32.asm 

C_SRCS += \
../src/CARMC_IO.c \
../src/CARMC_Interrupt.c \
../src/CARMC_Main.c \
../src/CARMC_PWM.c \
../src/CARMC_ctrl.c \
../src/CHE200_E2rom.c \
../src/DSP2803x_Adc.c \
../src/DSP2803x_Comp.c \
../src/DSP2803x_CpuTimers.c \
../src/DSP2803x_DefaultIsr.c \
../src/DSP2803x_ECan.c \
../src/DSP2803x_ECap.c \
../src/DSP2803x_EPwm.c \
../src/DSP2803x_EQep.c \
../src/DSP2803x_GlobalVariableDefs.c \
../src/DSP2803x_Gpio.c \
../src/DSP2803x_I2C.c \
../src/DSP2803x_Lin.c \
../src/DSP2803x_MemCopy.c \
../src/DSP2803x_PieCtrl.c \
../src/DSP2803x_PieVect.c \
../src/DSP2803x_Sci.c \
../src/DSP2803x_Spi.c \
../src/DSP2803x_SysCtrl.c \
../src/GPModule.c \
../src/can.c \
../src/cana.c \
../src/crtLoop.c \
../src/crtcmdConfig.c \
../src/diagFSM.c \
../src/eeprom.c \
../src/faultdetect.c \
../src/feedback.c \
../src/flash.c \
../src/high_fre.c \
../src/mtrFSM.c \
../src/mtr_learnexactoffset.c \
../src/mtr_learnfluex.c \
../src/mtr_learninitposition.c \
../src/mtr_learnoffset.c \
../src/mtr_learnrs.c \
../src/mtrfwd.c \
../src/oscview.c \
../src/peripheral.c \
../src/pid_reg3.c \
../src/spdLoop.c \
../src/sysConfig.c \
../src/sysFSM.c \
../src/sysInit.c \
../src/sysctrlFun.c \
../src/task.c \
../src/trqLmt.c \
../src/trqLoop.c \
../src/trqtable.c \
../src/variableInit.c \
../src/vdqLmt.c \
../src/voltLoop.c \
../src/weakcrtLoop.c 

C_DEPS += \
./src/CARMC_IO.d \
./src/CARMC_Interrupt.d \
./src/CARMC_Main.d \
./src/CARMC_PWM.d \
./src/CARMC_ctrl.d \
./src/CHE200_E2rom.d \
./src/DSP2803x_Adc.d \
./src/DSP2803x_Comp.d \
./src/DSP2803x_CpuTimers.d \
./src/DSP2803x_DefaultIsr.d \
./src/DSP2803x_ECan.d \
./src/DSP2803x_ECap.d \
./src/DSP2803x_EPwm.d \
./src/DSP2803x_EQep.d \
./src/DSP2803x_GlobalVariableDefs.d \
./src/DSP2803x_Gpio.d \
./src/DSP2803x_I2C.d \
./src/DSP2803x_Lin.d \
./src/DSP2803x_MemCopy.d \
./src/DSP2803x_PieCtrl.d \
./src/DSP2803x_PieVect.d \
./src/DSP2803x_Sci.d \
./src/DSP2803x_Spi.d \
./src/DSP2803x_SysCtrl.d \
./src/GPModule.d \
./src/can.d \
./src/cana.d \
./src/crtLoop.d \
./src/crtcmdConfig.d \
./src/diagFSM.d \
./src/eeprom.d \
./src/faultdetect.d \
./src/feedback.d \
./src/flash.d \
./src/high_fre.d \
./src/mtrFSM.d \
./src/mtr_learnexactoffset.d \
./src/mtr_learnfluex.d \
./src/mtr_learninitposition.d \
./src/mtr_learnoffset.d \
./src/mtr_learnrs.d \
./src/mtrfwd.d \
./src/oscview.d \
./src/peripheral.d \
./src/pid_reg3.d \
./src/spdLoop.d \
./src/sysConfig.d \
./src/sysFSM.d \
./src/sysInit.d \
./src/sysctrlFun.d \
./src/task.d \
./src/trqLmt.d \
./src/trqLoop.d \
./src/trqtable.d \
./src/variableInit.d \
./src/vdqLmt.d \
./src/voltLoop.d \
./src/weakcrtLoop.d 

OBJS += \
./src/BootLoader.obj \
./src/CARMC_IO.obj \
./src/CARMC_Interrupt.obj \
./src/CARMC_Main.obj \
./src/CARMC_PWM.obj \
./src/CARMC_ctrl.obj \
./src/CHE200_E2rom.obj \
./src/DSP2803x_Adc.obj \
./src/DSP2803x_CSMPasswords.obj \
./src/DSP2803x_CodeStartBranch.obj \
./src/DSP2803x_Comp.obj \
./src/DSP2803x_CpuTimers.obj \
./src/DSP2803x_DBGIER.obj \
./src/DSP2803x_DefaultIsr.obj \
./src/DSP2803x_DisInt.obj \
./src/DSP2803x_ECan.obj \
./src/DSP2803x_ECap.obj \
./src/DSP2803x_EPwm.obj \
./src/DSP2803x_EQep.obj \
./src/DSP2803x_GlobalVariableDefs.obj \
./src/DSP2803x_Gpio.obj \
./src/DSP2803x_I2C.obj \
./src/DSP2803x_Lin.obj \
./src/DSP2803x_MemCopy.obj \
./src/DSP2803x_PieCtrl.obj \
./src/DSP2803x_PieVect.obj \
./src/DSP2803x_Sci.obj \
./src/DSP2803x_Spi.obj \
./src/DSP2803x_SysCtrl.obj \
./src/DSP2803x_usDelay.obj \
./src/GPModule.obj \
./src/boot_start.obj \
./src/can.obj \
./src/cana.obj \
./src/crtLoop.obj \
./src/crtcmdConfig.obj \
./src/diagFSM.obj \
./src/dv64_32.obj \
./src/eeprom.obj \
./src/faultdetect.obj \
./src/feedback.obj \
./src/flash.obj \
./src/high_fre.obj \
./src/mtrFSM.obj \
./src/mtr_learnexactoffset.obj \
./src/mtr_learnfluex.obj \
./src/mtr_learninitposition.obj \
./src/mtr_learnoffset.obj \
./src/mtr_learnrs.obj \
./src/mtrfwd.obj \
./src/oscview.obj \
./src/peripheral.obj \
./src/pid_reg3.obj \
./src/spdLoop.obj \
./src/sysConfig.obj \
./src/sysFSM.obj \
./src/sysInit.obj \
./src/sysctrlFun.obj \
./src/task.obj \
./src/trqLmt.obj \
./src/trqLoop.obj \
./src/trqtable.obj \
./src/variableInit.obj \
./src/vdqLmt.obj \
./src/voltLoop.obj \
./src/weakcrtLoop.obj 

ASM_DEPS += \
./src/BootLoader.d \
./src/DSP2803x_CSMPasswords.d \
./src/DSP2803x_CodeStartBranch.d \
./src/DSP2803x_DBGIER.d \
./src/DSP2803x_DisInt.d \
./src/DSP2803x_usDelay.d \
./src/boot_start.d \
./src/dv64_32.d 

OBJS__QUOTED += \
"src\BootLoader.obj" \
"src\CARMC_IO.obj" \
"src\CARMC_Interrupt.obj" \
"src\CARMC_Main.obj" \
"src\CARMC_PWM.obj" \
"src\CARMC_ctrl.obj" \
"src\CHE200_E2rom.obj" \
"src\DSP2803x_Adc.obj" \
"src\DSP2803x_CSMPasswords.obj" \
"src\DSP2803x_CodeStartBranch.obj" \
"src\DSP2803x_Comp.obj" \
"src\DSP2803x_CpuTimers.obj" \
"src\DSP2803x_DBGIER.obj" \
"src\DSP2803x_DefaultIsr.obj" \
"src\DSP2803x_DisInt.obj" \
"src\DSP2803x_ECan.obj" \
"src\DSP2803x_ECap.obj" \
"src\DSP2803x_EPwm.obj" \
"src\DSP2803x_EQep.obj" \
"src\DSP2803x_GlobalVariableDefs.obj" \
"src\DSP2803x_Gpio.obj" \
"src\DSP2803x_I2C.obj" \
"src\DSP2803x_Lin.obj" \
"src\DSP2803x_MemCopy.obj" \
"src\DSP2803x_PieCtrl.obj" \
"src\DSP2803x_PieVect.obj" \
"src\DSP2803x_Sci.obj" \
"src\DSP2803x_Spi.obj" \
"src\DSP2803x_SysCtrl.obj" \
"src\DSP2803x_usDelay.obj" \
"src\GPModule.obj" \
"src\boot_start.obj" \
"src\can.obj" \
"src\cana.obj" \
"src\crtLoop.obj" \
"src\crtcmdConfig.obj" \
"src\diagFSM.obj" \
"src\dv64_32.obj" \
"src\eeprom.obj" \
"src\faultdetect.obj" \
"src\feedback.obj" \
"src\flash.obj" \
"src\high_fre.obj" \
"src\mtrFSM.obj" \
"src\mtr_learnexactoffset.obj" \
"src\mtr_learnfluex.obj" \
"src\mtr_learninitposition.obj" \
"src\mtr_learnoffset.obj" \
"src\mtr_learnrs.obj" \
"src\mtrfwd.obj" \
"src\oscview.obj" \
"src\peripheral.obj" \
"src\pid_reg3.obj" \
"src\spdLoop.obj" \
"src\sysConfig.obj" \
"src\sysFSM.obj" \
"src\sysInit.obj" \
"src\sysctrlFun.obj" \
"src\task.obj" \
"src\trqLmt.obj" \
"src\trqLoop.obj" \
"src\trqtable.obj" \
"src\variableInit.obj" \
"src\vdqLmt.obj" \
"src\voltLoop.obj" \
"src\weakcrtLoop.obj" 

C_DEPS__QUOTED += \
"src\CARMC_IO.d" \
"src\CARMC_Interrupt.d" \
"src\CARMC_Main.d" \
"src\CARMC_PWM.d" \
"src\CARMC_ctrl.d" \
"src\CHE200_E2rom.d" \
"src\DSP2803x_Adc.d" \
"src\DSP2803x_Comp.d" \
"src\DSP2803x_CpuTimers.d" \
"src\DSP2803x_DefaultIsr.d" \
"src\DSP2803x_ECan.d" \
"src\DSP2803x_ECap.d" \
"src\DSP2803x_EPwm.d" \
"src\DSP2803x_EQep.d" \
"src\DSP2803x_GlobalVariableDefs.d" \
"src\DSP2803x_Gpio.d" \
"src\DSP2803x_I2C.d" \
"src\DSP2803x_Lin.d" \
"src\DSP2803x_MemCopy.d" \
"src\DSP2803x_PieCtrl.d" \
"src\DSP2803x_PieVect.d" \
"src\DSP2803x_Sci.d" \
"src\DSP2803x_Spi.d" \
"src\DSP2803x_SysCtrl.d" \
"src\GPModule.d" \
"src\can.d" \
"src\cana.d" \
"src\crtLoop.d" \
"src\crtcmdConfig.d" \
"src\diagFSM.d" \
"src\eeprom.d" \
"src\faultdetect.d" \
"src\feedback.d" \
"src\flash.d" \
"src\high_fre.d" \
"src\mtrFSM.d" \
"src\mtr_learnexactoffset.d" \
"src\mtr_learnfluex.d" \
"src\mtr_learninitposition.d" \
"src\mtr_learnoffset.d" \
"src\mtr_learnrs.d" \
"src\mtrfwd.d" \
"src\oscview.d" \
"src\peripheral.d" \
"src\pid_reg3.d" \
"src\spdLoop.d" \
"src\sysConfig.d" \
"src\sysFSM.d" \
"src\sysInit.d" \
"src\sysctrlFun.d" \
"src\task.d" \
"src\trqLmt.d" \
"src\trqLoop.d" \
"src\trqtable.d" \
"src\variableInit.d" \
"src\vdqLmt.d" \
"src\voltLoop.d" \
"src\weakcrtLoop.d" 

ASM_DEPS__QUOTED += \
"src\BootLoader.d" \
"src\DSP2803x_CSMPasswords.d" \
"src\DSP2803x_CodeStartBranch.d" \
"src\DSP2803x_DBGIER.d" \
"src\DSP2803x_DisInt.d" \
"src\DSP2803x_usDelay.d" \
"src\boot_start.d" \
"src\dv64_32.d" 

ASM_SRCS__QUOTED += \
"../src/BootLoader.asm" \
"../src/DSP2803x_CSMPasswords.asm" \
"../src/DSP2803x_CodeStartBranch.asm" \
"../src/DSP2803x_DBGIER.asm" \
"../src/DSP2803x_DisInt.asm" \
"../src/DSP2803x_usDelay.asm" \
"../src/boot_start.asm" \
"../src/dv64_32.asm" 

C_SRCS__QUOTED += \
"../src/CARMC_IO.c" \
"../src/CARMC_Interrupt.c" \
"../src/CARMC_Main.c" \
"../src/CARMC_PWM.c" \
"../src/CARMC_ctrl.c" \
"../src/CHE200_E2rom.c" \
"../src/DSP2803x_Adc.c" \
"../src/DSP2803x_Comp.c" \
"../src/DSP2803x_CpuTimers.c" \
"../src/DSP2803x_DefaultIsr.c" \
"../src/DSP2803x_ECan.c" \
"../src/DSP2803x_ECap.c" \
"../src/DSP2803x_EPwm.c" \
"../src/DSP2803x_EQep.c" \
"../src/DSP2803x_GlobalVariableDefs.c" \
"../src/DSP2803x_Gpio.c" \
"../src/DSP2803x_I2C.c" \
"../src/DSP2803x_Lin.c" \
"../src/DSP2803x_MemCopy.c" \
"../src/DSP2803x_PieCtrl.c" \
"../src/DSP2803x_PieVect.c" \
"../src/DSP2803x_Sci.c" \
"../src/DSP2803x_Spi.c" \
"../src/DSP2803x_SysCtrl.c" \
"../src/GPModule.c" \
"../src/can.c" \
"../src/cana.c" \
"../src/crtLoop.c" \
"../src/crtcmdConfig.c" \
"../src/diagFSM.c" \
"../src/eeprom.c" \
"../src/faultdetect.c" \
"../src/feedback.c" \
"../src/flash.c" \
"../src/high_fre.c" \
"../src/mtrFSM.c" \
"../src/mtr_learnexactoffset.c" \
"../src/mtr_learnfluex.c" \
"../src/mtr_learninitposition.c" \
"../src/mtr_learnoffset.c" \
"../src/mtr_learnrs.c" \
"../src/mtrfwd.c" \
"../src/oscview.c" \
"../src/peripheral.c" \
"../src/pid_reg3.c" \
"../src/spdLoop.c" \
"../src/sysConfig.c" \
"../src/sysFSM.c" \
"../src/sysInit.c" \
"../src/sysctrlFun.c" \
"../src/task.c" \
"../src/trqLmt.c" \
"../src/trqLoop.c" \
"../src/trqtable.c" \
"../src/variableInit.c" \
"../src/vdqLmt.c" \
"../src/voltLoop.c" \
"../src/weakcrtLoop.c" 


